package server

import (
	"net/http"
	"github.com/go-chi/chi/v5"
)
// register user 
POST http://localhost:8080/users
Content-Type : application/json
{
	"name":"kasireddy"
	"email":"kasireddy2024@gmail.com"
	"password":"123@xyz"
}
POST http://localhost:8080/login
Content-Type : application/json
{
	"email":"kasireddy2024@gmail.com"
	"passwoed":"123456"
}